"""Knack-pin bumper pipeline.

State machine (idempotent, runs on every campaign invocation):

    on each run:
      1. PyPI has knack release w/ Python X.Y classifier?
            no  → pending (note: "awaiting knack PyPI release")
            yes → continue
      2. azure-cli's setup.py pin already at that knack version?
            yes → completed
            no  → continue
      3. open PR exists on our branch?
            yes → in_progress (pr=#)
            no  → continue
      4. branch from base → edit setup.py → push → open PR
            → in_progress (pr=new#)
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..azure_cli_upgrader.github_ops import (
    commit_all,
    create_branch,
    find_open_pr,
    open_draft_pr,
    push_branch,
)
from ..knack_upgrader import pypi
from . import edits


BRANCH_PREFIX = "campaign/knack-pin-"
PIN_FILE = Path("src/azure-cli-core/setup.py")
PR_TITLE_TEMPLATE = "Bump knack to {version}"


@dataclass(frozen=True)
class PinResult:
    status: str  # pending | in_progress | completed | failed
    pr: int | None = None
    notes: str = ""
    # Which phase the status applies to. "" (default) means "let the
    # framework pick the first phase"; "merged" is set explicitly when
    # there's nothing left to do (pin already at target).
    phase: str = ""


def run_pipeline(
    *,
    repo: str,
    repo_root: Path,
    new_minor: str,
    base_branch: str = "dev",
    tracking_issue: int | None = None,
    tracking_repo: str | None = None,
    dry_run: bool = False,
    force_recreate: bool = False,
) -> PinResult:
    """Run the knack-pin bumper. See module docstring for the state machine.

    ``repo_root`` is the local checkout of ``repo`` (provided by the
    workflow's clone step). We do not clone again.
    """
    # Stage 1: knack must be on PyPI first.
    status = pypi.check_pypi("knack", new_minor)
    if not status.supports or not status.latest_version:
        return PinResult(
            status="pending",
            notes=f"awaiting knack release with Python {new_minor} on PyPI",
        )
    target_version = status.latest_version

    # Stage 2: already at target?
    pin_file = repo_root / PIN_FILE
    if not pin_file.exists():
        return PinResult(
            status="failed",
            notes=f"{PIN_FILE} not found in {repo_root}",
        )
    content = pin_file.read_text(encoding="utf-8")
    current = edits.find_pin(content)
    if current is None:
        return PinResult(
            status="failed",
            notes=f"no knack pin found in {PIN_FILE}",
        )
    if current.version == target_version:
        return PinResult(
            status="completed",
            notes=f"setup.py already pins knack to {target_version}",
            phase="merged",
        )

    branch = f"{BRANCH_PREFIX}{new_minor}"

    # Stage 3: existing open PR.
    existing = find_open_pr(repo, branch)
    if existing is not None and not force_recreate:
        return PinResult(
            status="in_progress",
            pr=existing,
            notes=f"knack pin PR open (bumping to {target_version})",
            phase="created",
        )

    if dry_run:
        return PinResult(
            status="in_progress",
            notes=(
                f"[dry-run] would open PR bumping knack pin "
                f"{current.version} \u2192 {target_version}"
            ),
            phase="created",
        )

    # Stage 4: branch, edit, push, PR.
    create_branch(repo_root, branch, base=base_branch)
    new_content = edits.bump_pin(content, target_version)
    pin_file.write_text(new_content, encoding="utf-8")
    commit_all(repo_root, f"Bump knack to {target_version}")
    push_branch(repo_root, branch)

    body = _render_pr_body(
        current_version=current.version,
        new_version=target_version,
        new_minor=new_minor,
        tracking_issue=tracking_issue,
        tracking_repo=tracking_repo,
    )
    pr_number = open_draft_pr(
        repo=repo,
        title=PR_TITLE_TEMPLATE.format(version=target_version),
        body=body,
        head=branch,
        base=base_branch,
    )
    return PinResult(
        status="in_progress",
        pr=pr_number if pr_number > 0 else None,
        notes=f"opened PR bumping knack pin {current.version} → {target_version}",        phase="created",    )


def _render_pr_body(
    *,
    current_version: str,
    new_version: str,
    new_minor: str,
    tracking_issue: int | None,
    tracking_repo: str | None,
) -> str:
    lines = [
        f"Bumps `knack` from `{current_version}` to `{new_version}`, which declares",
        f"support for Python {new_minor}.",
        "",
        "Generated by the azure-cli-campaigns python-upgrade automation.",
    ]
    if tracking_issue is not None and tracking_repo:
        lines.append("")
        lines.append(f"Tracking: {tracking_repo}#{tracking_issue}")
    return "\n".join(lines) + "\n"
